### ISSUE TITLE
prepresessing-split by paragraph

### ISSUE THREAD

**Issue by un-lock-me** [altosaar/vae-lstm#1]
Thanks for sharing your code. can you please explain why did you calculate y in this way?
```
    x = data[:, i*num_steps:(i+1)*num_steps]
    y = data[:, i*num_steps+1:(i+1)*num_steps+1]
```
and if I want to feed the model with paragraph split rather than words, do you think I should follow the same approach except split them by paragraph and then keep the rest as it is?

Thanks again

**Comment by jaanaltosaar** [comment]
This is to predict the next step in each sequence. 

>> if I want to feed the model with paragraph split rather than words, do you think I should follow the same approach except split them by paragraph and then keep the rest as it is?

Yes, that's correct!

If I were you I would rewrite this in pytorch now though, it is much, much easier to use :)

**Comment by un-lock-me** [comment]
Im going to rewrite in Keras.
Do you think pytorch much easier than Keras?

**Comment by jaanaltosaar** [comment]
Yes I think pytorch is much easier.

**Comment by un-lock-me** [comment]
Last Question:)
Do you think this model may be good for feature extraction, topic modeling, not like perfect but good at some point as we can keep the context?

Thanks for helping out :)

**Comment by jaanaltosaar** [comment]
Hard to say—it is probably best to use BERT https://arxiv.org/abs/1810.04805

**Comment by un-lock-me** [comment]
Thank you so much :)

**Comment by saria85** [comment]
I just faced with a conflict, what will be the difference if I split the data by paragraph VS I give the timestamp of for example 50, with the hope of 50 words forms a paragraph. 
Can you please clarify this for me?

Sorry for the many questions under this issue and thanks for your time.
